### ISSUE TITLE
There is no function in the adapter to help users removeLiquidity from RAMSES

### ISSUE THREAD

**Issue by shealtielanz** [shieldify-security/Adapters-SPP#10]
## Description
In the docs and readme it is stated that users will have the functionality of adding and also removing Liquidity from RAMSES, the issue is there is no function in the adapter that allows this.
![Screenshot from 2024-04-27 23-18-09](https://github.com/shieldify-security/Adapters-SPP/assets/126171088/ae2272e7-04df-4a10-aa91-4bdefe150c50)
## Impact
Users not aware of how RAMSES works will be unable to redeem the liquidity added to RAMSES and also the protocol reputation will be affected by this due to failed promises.
## Recommendation
Create a functionality that lets users remove Liquidity from RAMSES or Correct the documentation.

**Comment by PossumLabsCrypto** [comment]
This featuer has been removed from the initial scope, users can go to Ramses and remove liquidity there.

**Comment by shealtielanz** [comment]
Heyy @PossumLabsCrypto Thanks for the feedback.
The reason users funds are used to add liquidity to RAMSES are to allow them gain profit from the LP shares of the PSM/WETH Pair.
That is the LP fees accrued but the issue is that users funds will be deposited there but the might not profit on the LP shares because RAMSES has a different way of distributing the fees accrued from a pair. 
I was researching and somethings feel a bit off about the protocol.
https://arbiscan.io/address/0xf5b610b8a2c79c75a62c9357d008b2fa9f242f68#code#F19#L214

I don’t think this functionality should be discarded in order to allow users gain profit from the Liquidity the added to RAMSES

**Comment by PossumLabsCrypto** [comment]
Users can remove their liquidity on Ramses or stake in the gauge or do whatever they like. The Adapter allows to create LPs with upfront yield, that´s all there is to it.
